# Generated by Django 3.2.4 on 2021-07-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_contato_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='mostrar',
        ),
        migrations.AlterField(
            model_name='contato',
            name='sobrenome',
            field=models.CharField(max_length=255),
        ),
    ]
