# Generated by Django 3.2.4 on 2021-07-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_auto_20210705_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='foto',
        ),
    ]
